import Head from "next/head";
import { sections } from "../data/sections";
import {
    BlogSection,
    ContentSection,
    Hero,
    HowToSection,
    FeaturesBanner,
    StatisticsBanner,
} from "../components/Home";
import playIcon from "../images/Web_arrow.svg";
import Image from "next/image";
import { createClient } from "contentful";

export async function getStaticProps() {
    const client = createClient({
        space: process.env.CONTENTFUL_SPACE_ID,
        accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
    });

    const res = await client.getEntries({
        content_type: "post",
        order: "-sys.createdAt",
    });

    return {
        props: {
            posts: res.items.slice(0, 3),
        },
        revalidate: 1,
    };
}

export default function Home({ posts }) {
    return (
        <div>
            <Head>
                <title>MKTFY Marketing Website</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
            <FeaturesBanner />

            {/* Quality Banner */}
            <section className="bg-quality-banner bg-cover bg-no-repeat py-[120px]">
                <div className="container h-full flex flex-wrap items-center">
                    <div className="flex flex-col">
                        <h2 className="font-bold text-lg text-white mb-5 max-w-[688px]">
                            MKTFY assures the quality of your purchase
                        </h2>
                        <p className="text-white font-semibold text-base max-w-text leading-text">
                            MKTFY wants to make sure that the stuff you buy is
                            in working order or your money back. Find out more
                            about our protection policy.
                        </p>
                    </div>
                    <Image src={playIcon} w={64} h={64} alt="play icon" />
                </div>
            </section>

            <HowToSection />

            {/* Businesses section */}
            <ContentSection
                imageOrientation="right"
                margins="mt-[120px] mb-[100px]"
                {...sections[0]}
            />

            {/* Donate section */}
            <ContentSection
                imageOrientation="left"
                margins="mt-[120px] mb-[240px]"
                {...sections[1]}
            />
            <StatisticsBanner />
            <BlogSection posts={posts} />
        </div>
    );
}
